spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**
                - Path=/api/v1/categories/**

            - id: search-service
              uri: lb://search-service
              predicates:
                -PATH=/api/v1/search/**

            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                -PATH=/api/v1/inventory/**

            - id: user-service
              uri: lb://user-service
              predicates:
                -PATH=/api/v1/auth/**


server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/