spring.application.name=search-service
server.port=8083

# ==========================================
# Elasticsearch Configuration
# ==========================================
spring.elasticsearch.uris=http://localhost:9200

# ==========================================
# Kafka Consumer Configuration
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=search-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# ==========================================
# Actuator & Logging
# ==========================================
management.endpoints.web.exposure.include=health,info
logging.level.org.springframework.kafka=INFO
logging.level.org.springframework.data.elasticsearch=INFO

