spring:
  application:
    name: search-service

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest

server:
  port: 8084




