spring:
  application:
    name: Order-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show:
      sql: true


server:
  port: